### ISSUE TITLE
Feedback for /Streams v4.2 VM Images

### ISSUE THREAD

**Issue by fang-wang** [IBMStreams/streamsx.documentation#103]
The document has instructions on how to import the v4.2 image to VirtualBox and provided the file to download: **_ova-streams-Vxxx-qse-v1.ova_**

But there is no information on how to get this ova file. Could you please add in the details on where to get this file. 

Thank you!

**Comment by jakrmpotic** [comment]
Here's a workaround:  I downloaded the VMWare package and used this process to run the image on VirtualBox: http://techathlon.com/how-to-run-a-vmdk-file-in-oracle-virtualbox/
For better performance, I created the virtual machine with 2 cores, 10000+ memory, and enabled “Use Host I/O Cache”.

**Comment by chanskw** [comment]
Documentation is fixed with information about how to use the VM image in virtual box.
