### ISSUE TITLE
Feedback for /docs/4.1/java/java-op-dev-guide/

### ISSUE THREAD

**Issue by debmalya** [IBMStreams/streamsx.documentation#111]
How to do unit test (JUnit) using java primitive operator? Particularly how to initialize OperatorContext?

**Comment by ddebrunner** [comment]
Streams provides a mock framework for Java primitive operators for testing.

https://www.ibm.com/support/knowledgecenter/SSCRJU_4.0.0/com.ibm.streams.spl-java-operators.doc/api/com/ibm/streams/flow/declare/package-summary.html#package_description
