### ISSUE TITLE
Search is broken after refactoring

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#119]
Need to wait for Google to index our page.  Removing existing links cause search to break.

**Comment by jakrmpotic** [comment]
@chanskw When does Google index the page? Do you need to send a request or is there a regular, automated schedule?

**Comment by chanskw** [comment]
Google will eventually index.  To have schedule index, we will need to pay for the service.

I thought your were asking about the index page that is in the repository.  Please just leave in that page.
