### ISSUE TITLE
Feedback for /

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.documentation#123]
In the **IBM Streams Python support** section of [IBM Streams documentation](http://ibmstreams.github.io/streamsx.documentation/index.html), the "API reference (v1.6)" link takes me to the [streamsx.rest module](http://ibmstreams.github.io/streamsx.topology/doc/releases/1.6/pythondoc/streamsx.rest.html). I think we should be pointing users to the [main Python doc page](http://ibmstreams.github.io/streamsx.topology/doc/releases/1.6/pythondoc/index.html).

**Comment by jakrmpotic** [comment]
I fixed it in my branch 411jasna, but haven't created a pull request yet.
<img width="1050" alt="screen shot 2017-04-12 at 12 03 59 am" src="https://cloud.githubusercontent.com/assets/24479385/24945340/b514f142-1f13-11e7-87e9-3ccd7b760bf7.png">
