### ISSUE TITLE
Discussion of Python application deployment options is misleading

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.documentation#128]
From here:
http://ibmstreams.github.io/streamsx.documentation/docs/python/1.6/python-appapi-devguide/

I think this paragraph:

-  As a Streams distributed application (DISTRIBUTED). When running in this mode, the application produced will be deployed automatically on your IBM Streams instance.
- As a Streams Application Bundle file (BUNDLE). When running in this mode, the application produces a SAB file that you can then deploy on your IBM Streams or Bluemix Streaming Analytics service instance by using the streamtool submitjob command or by using the application console
 -  As a stand-alone application (STANDALONE). When running in this mode, the application produces a Streams Application Bundle file (SAB file) but rather than submitting the SAB file to an instance, the bundle is executed. The bundle runs within a single process and can be terminated with Ctrl-C interrupts.
 

Is incorrect, because it makes it sound like a .sab file is only created sometimes. From what I understand, a bundle is always created when you compile the application.  The different execution options determine _what_ is done with the bundle (submitted automatically to the instance, executed as a single process, or manually submitted to the instance).

**Comment by ddebrunner** [comment]
When using distributed or streaming analytics (or even standalone) by default the bundle is just a transient object which the client does not see. So in someways the bundle is not created, as the user never sees it.

E.g. as a Python developer who has never used streams, and only submits to the streaming analytics service they may never see, care or have knowledge about a bundle.
