### ISSUE TITLE
Feedback for /docs/4.1/cybersecurity/cybersecurity-getting-started/ - image size

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#14]
@cancilla 
I think the images at the bottom are too small.  And not sure if we really want the user to click on the image to see the content.

Can we make it bigger?  Better yet, maybe just a quick video to show those steps?

**Comment by cancilla** [comment]
The images are supposed are just supposed to aid the reader if they are unclear where they are supposed to be. I think the steps are clear what needs to be done. Making the images bigger will clutter the guide and make it more difficult to read.

**Comment by markheger** [comment]
The guide is stable for years and still valid for Streams 4.3 http://ibmstreams.github.io/streamsx.documentation/docs/4.2/cybersecurity/cybersecurity-getting-started/
Image size is ok, no need to change anything
