### ISSUE TITLE
Update 1.6 dev gde Lambda function support

### ISSUE THREAD

**Issue by jakrmpotic** [IBMStreams/streamsx.documentation#142]
Topic to be updated: http://ibmstreams.github.io/streamsx.documentation/docs/python/1.6/python-appapi-devguide-4/

Lambda functions are supported as functions that source, transform, filter or sink streams.

In a notebook environment this simplifies development of applications by not forcing a separate function (in a separate module) to manipulate the stream. For example, this is now valid:
filtered = source.filter(lambda tuple : tuple.startswith("d"))

**Comment by markheger** [comment]
please re-open if still valid

unclear what is missing
