### ISSUE TITLE
Feedback for /docs/python/1.6/python-appapi-devguide-3/

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.documentation#145]
I tried to follow [this guide](http://ibmstreams.github.io/streamsx.documentation/docs/python/1.6/python-appapi-devguide-3/) in the 4.2.0 QSE and I have the following observations:

In step 3, we should give directions on how to update to the latest version of the topology toolkit if there is a newer release than that installed in the QSE.
In step 4:
a) It would be helpful to add tips for using Anaconda, e.g. adding anaconda to your path, creating the environment, and setting up a source environment. The tutorial for developing without an install already has this information.
b) The QSE already has Python 3 installed, so it is good to state that.

These comments also apply to the [Python API Doc](http://ibmstreams.github.io/streamsx.topology/doc/pythondoc/index.html):

c) Future and requests are not present in the Anaconda package (some versions).  They are also needed if you install Python from source.  Are the additional dependencies not listed deliberately because they can change quickly? Or  is it a good idea to document what additional packages are needed?
d) If you build Python from source you might need to set `LD_LIBRARY_PATH=/usr/local/lib` or wherever Python is installed otherwise you get this error when trying to run `python3` after a  successful installation: `python3: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory`
e)  According to the API doc](http://ibmstreams.github.io/streamsx.topology/doc/pythondoc/index.html#ibm-streams-on-premises), you are required to set `PYTHONHOME` ,  but in Step 5 of the guide it says I should set `PYTHONPATH`. Which is correct?  Do you have to set PYTHONPATH if you use pip to install streamsx?

**Comment by ddebrunner** [comment]
>  It would be helpful to add tips for using Anaconda, e.g. adding anaconda to your path, creating the environment, and setting up a source environment.

As an observation after installing an Anaconda with 3.5  I've never needed to do any of those items.

> If you build Python from source

Installing Python from source is actually a somewhat non-trivial process, really suitable for an expert. I'm not sure our docs is the correct place to walk someone through this. Hence, use Anaconda, it's simple. :-)

> e) ... Which is correct?

Both.

> Do you have to set PYTHONPATH if you use pip to install streamsx?

No.

**Comment by chanskw** [comment]
I am confused by this too:

"e) According to the API doc](http://ibmstreams.github.io/streamsx.topology/doc/pythondoc/index.html#ibm-streams-on-premises), you are required to set PYTHONHOME , but in Step 5 of the guide it says I should set PYTHONPATH. Which is correct? Do you have to set PYTHONPATH if you use pip to install streamsx?"

My assumption is that PYTHONHOME does not need to be set anymore.  But in the Topology documentation, it is saying that it needs to be set.

**Comment by ddebrunner** [comment]
PYTHONHOME must be set to execute streaming applications built by the Python application API.

> My assumption is that PYTHONHOME does not need to be set anymore.

@chanskw  What lead you to that assumption?

**Comment by chanskw** [comment]
I may have confuse it with the requirement with PYTHONPATH?  

When we build the application locally and want to run it on Bluemix, do we need to have PYTHONHOME set or unset?

**Comment by chanskw** [comment]
I can now see that this doc refers to on-prem, while my assumption applies to building application for the Streaming Analytics for Bluemix.  I think the on-prem and bluemix separation confused me a bit here.

**Comment by ddebrunner** [comment]
> When we build the application locally and want to run it on Bluemix, do we need to have PYTHONHOME set or unset?

PYTHONHOME is only required when **running** the streaming application, i.e. executing the bundle in standalone or submitting to an instance. (The instance must have PYTHONHOME set, not the client submitting the app).

**Comment by natashadsilva** [comment]
When installing Anaconda on my Mac it set up the path variables for me.  On Linux it is not done automatically as far as I can tell.

> PYTHONHOME is only required when running the streaming application, i.e. executing the bundle in standalone or submitting to an instance. (The instance must have PYTHONHOME set, not the client submitting the app).
So, to be clear, you  need to set PYTHONPATH for development but only if you downloaded the toolkit from Github or are using the version in the product.  PYTHONHOME is needed if you are submitting your job to an instance or running in standalone mode.

**Comment by ddebrunner** [comment]
With the Linux install for me it was done. There was a question at the end of the install (defaulting to yes) asking if I wanted to add including the Anaconda path to bashrc.

**Comment by natashadsilva** [comment]
OK.  At a minimum the doc should be updated to state that PYTHONHOME needs to be set if they want to use distributed mode.  It would also be helpful to update either  section 3.6 or 3.8 with detailed snippets on how to run in Distributed mode.  It is easy enough to do in the QSE because all the environment variables are set by default but running in DISTRIBUTED mode else where requires a bit of digging in the doc.

**Comment by markheger** [comment]
covered in setup instructions:
http://ibmstreams.github.io/streamsx.documentation/docs/python/1.6/python-appapi-devguide-2/
