### ISSUE TITLE
Feedback for /docs/4.1/cybersecurity/cybersecurity-getting-started/ - too vm specific

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#15]
@cancilla  
For the cybersecurity toolkit, I think the install instructions are valid for non-vm / docker install.  We have QSE for Linux which is really a normal Streams install.  In that case, the user still has to install the dependencies?

**Comment by markheger** [comment]
> We have QSE for Linux which is really a normal Streams install. In that case, the user still has to install the dependencies?

yes
