### ISSUE TITLE
Feedback for /docs/java/java-appapi-devguide/

### ISSUE THREAD

**Issue by tstevko-weather** [IBMStreams/streamsx.documentation#152]
Unless I'm really mistaken, the following line is no longer accurate for 4.2+:
```text
Lastly, nested parallelism is not supported, so invoking parallel() on a TStream that’s already been parallelized will throw an exception.
```

**Comment by ddebrunner** [comment]
While nested parallelism is supported in Streams 4.2 using SPL, it is not yet supported for Java/Python.

**Comment by tstevko-weather** [comment]
Gotcha. Thanks!

From: Dan Debrunner <notifications@github.com> <notifications@github.com>
Reply: IBMStreams/streamsx.documentation
<reply@reply.github.com>
<reply@reply.github.com>
Date: April 20, 2017 at 11:38:22
To: IBMStreams/streamsx.documentation
<streamsx.documentation@noreply.github.com>
<streamsx.documentation@noreply.github.com>
Cc: Ted Stevko <ted.stevko.contractor@weather.com>
<ted.stevko.contractor@weather.com>, Author <author@noreply.github.com>
<author@noreply.github.com>
Subject:  Re: [IBMStreams/streamsx.documentation] Feedback for
/docs/java/java-appapi-devguide/ (#152)

While nested parallelism is supported in Streams 4.2 using SPL, it is not
yet supported for Java/Python.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/IBMStreams/streamsx.documentation/issues/152#issuecomment-295850553>,
or mute the thread
