### ISSUE TITLE
Feedback for streamsx.documentation/docs/python/1.6/python-appapi-devguide/

### ISSUE THREAD

**Issue by pamlane** [IBMStreams/streamsx.documentation#156]
My comments and questions are in the attached Word doc and apply to the following files:
python-appapi-devguide-2.md
python-appapi-devguide-2a.md
python-appapi-devguide-3.md
python-appapi-devguide-4.md
python-appapi-devguide-5.md
python-appapi-devguide.md

[Developing IBM Streams Applications with Python - Pam.docx](https://github.com/IBMStreams/streamsx.documentation/files/953463/Developing.IBM.Streams.Applications.with.Python.-.Pam.docx)

**Comment by wmarshall484** [comment]
Attaching a doc file isn't the typical github workflow we use. Typically reviews like this are done in-line in the issue, or even better as a pull request from a fork you create.

**Comment by wmarshall484** [comment]
> an SAB file

I think **a** SAB file is correct.
