### ISSUE TITLE
Python API tutorials don't cover command for Windows and Mac

### ISSUE THREAD

**Issue by pamlane** [IBMStreams/streamsx.documentation#158]
For http://ibmstreams.github.io/streamsx.documentation/docs/python/1.6/python-appapi-devguide-2a/#29-the-complete-application and http://ibmstreams.github.io/streamsx.documentation/docs/python/1.6/python-appapi-devguide-3/, the command-line examples (with one exception) cover only unix. The examples should also cover the related Windows and OSX equivalent commands.

**Comment by markheger** [comment]
devguide covers notebooks in the sections mentioned above, and Jupyter notebooks are OS independent.
Python commands shall be OS independent, too.
