### ISSUE TITLE
Feedback for /docs/4.1/messaging/kafka-operators-getting-started/

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.documentation#167]
Using Quick Start 4.2 edition and IBM Java included in Streams, with kafka_2.11-0.11.0.0.tgz I had to replace "-Xloggc" with "-Xverbosegclog" in the kafka/bin/kafka-run-class.sh script. 

The solution was in this link: https://www.ibm.com/support/knowledgecenter/en/SSPFMY_1.3.3/com.ibm.scala.doc/tshoot/iwa_ts_kfk_c.html

**Comment by markheger** [comment]
outdated, messaging toolkit is deprecated
kafka toolkit guide is up to date
