### ISSUE TITLE
Feedback for /docs/drafts/java-op-dev-guide/ - Creating your First Java Operator

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#17]
As a general comment, I think the doc lacks the details that I am looking for.  With the videos, we should focus less on documenting the steps required to do certain things in Studio.  Instead, I was hoping we take a more command line approach so we can bring out some of the basic concepts as discussed before.

For example, in the Java Native Function guide, we use the command line to build the function.  This involves building the java code, as well as calling spl-make-toolkit to to build the toolkit.  This is important, because it is in the spl-make-toolkit step where we take the annotations from the java code and build the function model.  The function model is a key resource to allowing the SPL code to see the function.  

Because we focus solely on Studio, these points are not discussed in the Java Operator Guide.  And these are the conceptual details that I am looking for.

In "Creating First Java Operator"

I found it the list of annotations very disconcerting.  Part of the reason is probably because I never really see the Java code and see where it fits in the bigger picture.  Perhaps we should have code that demonstrate the basic Java operator, and then slowly add the annotations and talk about what they mean.

I would organize this section like this:

1)  Show the most barebone Java operator
2)  Talk about how it extends AbstractOperator
3)  Talk about at a minimum, add the required annotations
4)  Talk about at a minimum, that we need to implement the process method.

Following the Create First Java Operator, we should have a "Building Java Operator" section
- At the command line, how to build this operator?
- spl-make-toolkit 
- what happens under the cover and talk about that we have generated the operator model, which is required for the SPL code to see this operator

Then we talk about testing operator.

**Comment by Alex-Cook4** [comment]
This feedback has previously been incorporated. Thanks @chanskw!
