### ISSUE TITLE
streamsx doc pages need a Notices topic

### ISSUE THREAD

**Issue by pamlane** [IBMStreams/streamsx.documentation#175]
The Streams documentation pages (http://ibmstreams.github.io/streamsx.documentation/index.html) needs to include a Notices topic similar to the one that is included in the Bluemix docs:
https://console.bluemix.net/docs/navigation/notices.html#notices

The attached file is actually a .md file based on the Bluemix topic:
[notices.txt](https://github.com/IBMStreams/streamsx.documentation/files/1432347/notices.txt)
The file should be customized for Streams (terms and privacy policy particular.y), and reviewed by legal.

**Comment by ddebrunner** [comment]
I'm not sure an IBM notices is the correct form. This is an open source project released under the Apache Licence.

**Comment by natashadsilva** [comment]
@pamlane Is it ok to close this?
