### ISSUE TITLE
Feedback for /docs/drafts/java-op-dev-guide/ - testing

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.documentation#18]
We should encourage testing of Java operators using the Java mock framework.

**Comment by chanskw** [comment]
We will... but maybe in the next go around..

Trying tog et the basics in and then we will talk more about testing and test automation

**Comment by Alex-Cook4** [comment]
Can you point me to information about using the Java mock framework? Are we talking about JUnit?

**Comment by ddebrunner** [comment]
Yes JUnit or similar tools.

IBM Streams provides a mock framework to test Java primitive operators, creating an arbitrary graph that includes the operator under test and the ability to execute it. Tuples can be injected into input ports and captured from output ports, so you can write assertion based testing using tools like JUnit.

http://www-01.ibm.com/support/knowledgecenter/api/content/SSCRJU_4.0.0/com.ibm.streams.spl-java-operators.doc/api/com/ibm/streams/flow/javaprimitives/package-summary.html?locale=en

Examples exist in some of the toolkits here, such as streamsx.inet

**Comment by markheger** [comment]
part of streamsx.testing
https://github.com/IBMStreams/streamsx.testing/blob/develop/examples/operators/tests/java/src/examples/operators/tests/TestMultiplyBy.java
