### ISSUE TITLE
Feedback for /docs/4.2/qse-install-docker/

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.documentation#183]
Hello.  The same issue noted for mac ([install Streams prereq packages with yum] fails) happens for me on linux.  The same fix works as well.  You may just want to note it is for linux and mac.  Has anyone tried on windows?  I assume it would be a problem there as well.

**Comment by natashadsilva** [comment]
Thanks for pointing this out, I've updated the doc.
