### ISSUE TITLE
Feedback for /docs/beamrunner/beamrunner-2-install/

### ISSUE THREAD

**Issue by mikespicer** [IBMStreams/streamsx.documentation#184]
Why is A Red Hat Enterprise Linux 6 or 7 environment recommended in the before you execute section?  It worked fine on my Mac.

**Comment by ddebrunner** [comment]
That only makes sense if you have a local Streams install you are using for the sab build. 
And then it's not a recommendation but required, and required that your local os matches the version of your service. Also the OS in that case can be CentOs.

**Comment by mikespicer** [comment]
OK, that makes sense but is not clear from the documentation as it is currently, so that should be changed.

**Comment by pamlane** [comment]
This section is now on https://pamlane.github.io/streamsx.documentation/docs/beamrunner/beamrunner-2b-sas/. With all the re-org and updates that have happened, I'm not clear on whether this has been resolved or not. @ddebrunner can you advise?

**Comment by ddebrunner** [comment]
@pamlane Has not been resolved.  This is the offending paragraph.

For best results, use a Red Hat Enterprise Linux 7 environment for submitting Beam applications to the Streaming Analytics service in IBM Cloud (formerly IBM Bluemix). Using a Red Hat Enterprise Linux 6 environment can result in version incompatibility errors if you compile your application locally and then submit it IBM Cloud.

**Comment by pamlane** [comment]
Hi Dan,
 
I've played around with this paragraph, and I really have no idea what I'm saying. 
 
Here's the original:
For best results, use a Red Hat Enterprise Linux 7 environment for submitting Beam applications to the Streaming Analytics service in IBM Cloud. Using a Red Hat Enterprise Linux 6 environment can result in version incompatibility errors if you compile your application locally and then submit it IBM Cloud.
 
Here's your comment:
That only makes sense if you have a local Streams install you are using for the sab build.And then it's not a recommendation but required, and required that your local os matches the version of your service. Also the OS in that case can be CentOs.
 
I tried this, but I don't know how to address the "local os must match service version" (how would the user determine the version of the service?) or the "can be CentOS" part.
If you compile your Beam application locally, you must use a Red Hat Enterprise Linux 7 environment to submit it to the Streaming Analytics service in IBM Cloud.
Do you have any suggestions?
 
Thanks,
Pam
 
 
----- Original message -----From: Dan Debrunner <notifications@github.com>To: "IBMStreams/streamsx.documentation" <streamsx.documentation@noreply.github.com>Cc: Pam Lane <pamlane@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBMStreams/streamsx.documentation] Feedback for /docs/beamrunner/beamrunner-2-install/ (#184)Date: Fri, Jul 20, 2018 12:02 PM 
@pamlane Has not been resolved. This is the offending paragraph.
For best results, use a Red Hat Enterprise Linux 7 environment for submitting Beam applications to the Streaming Analytics service in IBM Cloud (formerly IBM Bluemix). Using a Red Hat Enterprise Linux 6 environment can result in version incompatibility errors if you compile your application locally and then submit it IBM Cloud.

**Comment by ddebrunner** [comment]
@pamlane 
The offending paragraph can be removed.

https://github.com/IBMStreams/streamsx.documentation/issues/184#issuecomment-406698211
