### ISSUE TITLE
Feedback for /docs/beamrunner/beamrunner-2-install/

### ISSUE THREAD

**Issue by mikespicer** [IBMStreams/streamsx.documentation#185]
The description of setting up the VACP file is confusing and error prone.  This page describes how to copy the vcap file and set the environment variables to pint to the file and set the service name before explaining how to get the credentials to put in the vcap file. It also didn't seem to mention that the service name in the vcap file must match the STREAMING_ANALYTICS_SERVICE_NAME environment variable.

**Comment by pamlane** [comment]
Fixed. The VCAP procedure didn't indent substeps properly in the VCAP section.
https://pamlane.github.io/streamsx.documentation/docs/beamrunner/beamrunner-2b-sas/
