### ISSUE TITLE
Feedback for /docs/beamrunner/io/ - grammar mistakes

### ISSUE THREAD

**Issue by bmel** [IBMStreams/streamsx.documentation#186]
There are at least two mistakes (missing 'that', 'and') in this sentence:
> The object storage system requires bucket names **[that?]** must be globally unique and DNS-compliant; names must be between 3 and 63 characters long **[and?]** must be made of lowercase letters, numbers, and dashes.

**Comment by pamlane** [comment]
Fixed. Changed to 
The object storage system requires that bucket names must be globally unique and DNS-compliant. Names must be 3 - 63 characters long and must consist of lowercase letters, numbers, and dashes.

**Comment by bmel** [comment]
Nice!
