### ISSUE TITLE
Feedback for /docs/4.1/java/java-op-dev-guide/

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.documentation#30]
1. the video does not show.  There is audio but the video window is blank on FireFox, works all right in chrome.
2. Building java operator with studio...step 4 should be and then press Finish since you need to exit that dialog to create the project and then proceed to the next part.
  2a) Step 6 of same dialog the ordering is backward from the dialog and is confusing, should be changed to be:  Set the namespace to stringToCaps and the Name to be StringToCaps.  
   2b) What about the copying or passing through of the other attributes to the output tuple??  The example should include that since it is almost always needed and it does show up as an outTuple.assign(tuple) in the sample generated code.
3. Best practices tip regarding the samples jar etc... This is done automatically within Studio and the user does not need to worry about this.  This may needlessly complicate things for the Studio user.
4. The structure graphic should be split to show the default structure and then the actual content from the sample project just built.  Without this it is confusing as some of the directories are empty and a new user would not know whether that was correct.
5. SPL toolkit dependency section...not sure why Studio is not being discussed here since it will help create info.xml in the project wizard.
6. Any links to other documentation should open in a new tab or window.  It is hard to navigate back to the document when you land in the Streams Knowledge Center....for example the Parameter Annotation Javadoc.
7. For the parameters section I found step 1 to be confusing and not really required.  I would suggest changing this section to show examples of the most common parameters types and usage.  The basic steps are 1. create private member for parameter, 2. create setter method for parameter, 3. add @annotation on setter method, 4. create getter method, 5. use in code (typically initialize of process to control things.
8. I would leave out the metrics REST API section for this guide and simply indicate the metrics are available in console or studio.
9. createCustomMetric annotation is missing the description
10. I would suggest changing the outline to have 3 example operators that align with the wizards in Studio, consumes and produces tuples (general operator), produces tuples (source operator), consumes tuples (sink).

**Comment by Alex-Cook4** [comment]
These comments were addressed as of merge of #47 pull request.
