### ISSUE TITLE
Feedback for /docs/4.1/java/java-op-dev-guide/

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.documentation#31]
An example that shows how to wrap an existing Java library into a streams operator would be helpful as a separate guide showing the steps to wrap something.

**Comment by Alex-Cook4** [comment]
@petenicholls When you say "an example showing how to wrap an existing Java library" do you mean simply converting a piece of Java code to Java Operator code in the simplest manner possible? Maybe a more complicated version of what we did here: http://ibmstreams.github.io/streamsx.documentation/docs/4.1/java/java-op-dev-guide/#creating-a-source-operator?

**Comment by markheger** [comment]
http://ibmstreams.github.io/streamsx.documentation/docs/java/java-appapi-files-in-app-bundle/
