### ISSUE TITLE
Feedback for /docs/4.1/java/java-appapi-devguide/ - invoking spl code

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#40]
@wmarshall484  Is this exmple incorrect ?  From section about invoking spl operator. 

StreamSchema rstringSchema = Type.Factory.getStreamSchema("tuple<rstring rstring_attr_name>");

SPLStream splInputStream = SPLStreams.convertStream(strings, new BiFunction<String, OutputTuple, OutputTuple>(){
  @Override
  public OutputTuple apply(String input_string, OutputTuple output_rstring) {
    output_rstring.setString("rstring_attr_name", input_string);
      return output_rstring;
    }
  }, rstringSchema);

In convertStream, we have two OutputTuple. Should one of them be StreamSchema?

**Comment by markheger** [comment]
sample is correct, third parameter is of type `com.ibm.streams.operator.StreamSchema`
