### ISSUE TITLE
Feedback for /

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#49]
Product Documentation page should point here instead:
http://www.ibm.com/support/knowledgecenter/#!/SSCRJU/SSCRJU_welcome.html

**Comment by chanskw** [comment]
Alex, can you please fix this for me?  The link seems wrong.

Thanks!

**Comment by Alex-Cook4** [comment]
Fixed: commit https://github.com/IBMStreams/streamsx.documentation/commit/0a42e999c7b7808b5d1face0dd70d64de1facb78 

[Streams Product Documentation (versions 1.2.1 - current)](http://www.ibm.com/support/knowledgecenter/SSCRJU/SSCRJU_welcome.html)

**Comment by chanskw** [comment]
did you also fix the link at the top .. "product documentation" link on the navigation bar?

**Comment by Alex-Cook4** [comment]
I don't think so, but when I click on it I get: http://www-01.ibm.com/support/knowledgecenter/#!/SSCRJU/SSCRJU_welcome.html

**Comment by chanskw** [comment]
Please also update the top link.  I does not take me to the right place for Safari.

**Comment by Alex-Cook4** [comment]
I have committed a fix that should work for Safari. Could you please test and close if it works?
