### ISSUE TITLE
Add Edit Page button

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#50]
Still seems to hard to contribute documentation.
Add a button to take contributor directly to page to edit.

**Comment by chanskw** [comment]
I see that we have added the "Edit Button"

But do we really want it to be at the bottom of the index on the left hand side?
If the index is really big, the button may not be visible until the user scroll.  Is there a better place for this?

**Comment by Alex-Cook4** [comment]
I've tried a few different locations and ended up liking that location the best. I think that it is still visible for even our biggest indexes currently, but you're right that it could become a concern in the future. Here is a screenshot of what it looks like under the title. What do you think? 

![image](https://cloud.githubusercontent.com/assets/12279352/13931954/c68b58ba-ef73-11e5-834e-8f0836c3dd01.png)

![image](https://cloud.githubusercontent.com/assets/12279352/13931925/9b0e2226-ef73-11e5-943a-8dfe1d845733.png)

**Comment by Alex-Cook4** [comment]
Also at the top of the index: <br>

![image](https://cloud.githubusercontent.com/assets/12279352/13932004/135fa5f6-ef74-11e5-9f8f-22826f679859.png)

I personally like the current button the best because it is more subtle. The other ones seem too prominent...the documentation is primarily for the content, not for editing. I think the button draws too much attention if it is directly under the title especially.

**Comment by chanskw** [comment]
I agree... can we make it smaller and be put on the right hand side of the title?

**Comment by Alex-Cook4** [comment]
I think this looks pretty good: 

![image](https://cloud.githubusercontent.com/assets/12279352/13933415/1e7562b2-ef7b-11e5-92d0-22e73154ce20.png)

**Comment by chanskw** [comment]
:+1:

**Comment by Alex-Cook4** [comment]
We can do this, but first in every document we will have to:
1. Remove titles that are done with markdown # since we need to use the title from the document property at the top. Here is redundant titling: 

```
---
layout: docs
title:  Installing Streams Quick Start Edition Docker
description:  Installation Guide for IBM Streams Quick Start Edition Docker
weight: 30
published: false
---

**(Coming Soon...)**

# Installing Streams Quick Start Edition Docker Image
```

2. Once that is done, the easy part is moving the button :)

**Comment by chanskw** [comment]
perhaps we should just do it now, since we have a relatively small set of files.

If we wait longer, our file set will get bigger.

**Comment by Alex-Cook4** [comment]
Agreed. I will try to do it this afternoon and deliver.

**Comment by Alex-Cook4** [comment]
Delivered.
