### ISSUE TITLE
Tutorial for streamsx.topology project

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#52]
I think it will be good if we create a step-by-step tutorial to show people how to use the new Java Application APIs.

Idea on outline:
1.  Use case / scenario that we are trying to solve with the tutorial
2.  Introduction to the API
3.  Reading csv data from a file
4.  Printing data
5.  Running the application (embedded mode)
6.  Transforming data
7.  Filtering data
8.  Using Window to calculate average
9.  Putting it all together
10.  Running the application in distributed mode
11.  Monitoring and debugging the application
12.  Switching from a file data source to a more realistic datasource (e.g. Kafka)
13.  Switching the print to a more realistic datasink (e.g. HDFS / HBase)
14.  More advanced analytics using a SPL toolkit (e.g. time series / R)
15.  Creating a custom data source
16.  Creating a custom data sink

**Comment by chanskw** [comment]
@ddebrunner @petenicholls @wmarshall484 - Please review the outline and let me know what you think.

I am unsure when we can do this, but thought I would document what I am thinking.  This one will a bit more detailed than the development guide and would provide "step-by-step" instructions on how to use the APIs.  Think of the "Streams Introductory Lab", this is similar, but focus on the topology APIs.  The idea is to take the user through the steps of solving a common problem.

I have directed new users to the topology development guide, it seems that people still have trouble getting started with that information.  I think the difficulty is in how to envision a Streams pipeline and working with a new "programming model".    In this tutorial, we will show user how to build a realistic application.  Each module will be built on top of the previous one.  We will talk about the steps in building the application and some of the best practices along the way.  We should also provide code projects where people can use as starting points in building the application.

**Comment by chanskw** [comment]
Maybe I should have opened this in the tutorial project.... but will leave it here for now.

**Comment by ddebrunner** [comment]
FYI - For Quarks I started to add some visual aids that try to explain streaming, here:

https://issues.apache.org/jira/browse/QUARKS-37

The same concept could be used for the topology api as well as IBM Streams.

**Comment by ddebrunner** [comment]
> Reading csv data from a file

I think a tutorial has a better chance of instilling the streaming concept across if it starts out with continuous data rather than looking like a batch system by reading files.

**Comment by chanskw** [comment]
I agree... but for someone new to try this out... a file is their first step.
They usually have some sample data where they want to try processing... and then move to a more continuous live system.  This is why I added a csv file first, and then moving to a more realistic source later.

**Comment by ddebrunner** [comment]
> a file is their first step.

Why? 

It's just as easy to use live data from something like NextBus and it helps cement the streaming paradigm.

Also if we want the tutorial to work on Bluemix then files are tricky.

**Comment by chanskw** [comment]
Looking from someone who is trying out Streams and topology APIs, and evaluating if Streams is a good fit, the user usually already has some data that they are interested in using Streams to process.  From this perspective, they are interested in how easy it is to process their data, what kind of analytics they can perform.  In this case, the user will have some sample data already stored in some files.

While I agree that we should try to use a live data stream, I do not think we should avoid talking about using a FileSource.  It's great that we can ingest from HTTP/Kafka/MQTT easily, but at the same time, we need to make sure this initial evaluation process can be performed quickly.  I have seen people struggle with ingesting data from a file source... and unsure even how to get their own data into the application.  Therefore, I think it is important that we go through this in a tutorial.  At the same time, stress that we can ingest from live data source and show how we can also accomplish that easily.

**Comment by ddebrunner** [comment]
Just a note that use of files rules out running the tutorial on Bluemix.

**Comment by markheger** [comment]
Development guide exists and needs to be updated.
Updates are covered by 
https://github.com/IBMStreams/streamsx.documentation/wiki/ICP4D-Updates-for-Python-development-guide
