### ISSUE TITLE
Review Getting Started with Kafka Operators

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.documentation#59]
Could someone review https://github.com/IBMStreams/streamsx.documentation/blob/gh-pages/docs/4.1/messaging/kafka-operators-getting-started.markdown so that we can publish? Please provide feedback so that I can make changes. Thanks!

**Comment by chanskw** [comment]
@Alex-Cook4 Review done, please check it out.

**Comment by chanskw** [comment]
+1  Looks great.  Added a few minor comments, but overall, it looks good!
