### ISSUE TITLE
Feedback for /docs/drafts/java-function-dev-guide/

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.documentation#6]
For the section on testing it's probably good to point out that since the function is just Java one can test its implementation using standard Java techniques, such as JUnit.

Then the testing currently described is testing that it works in an SPL environment, which is a follow on to testing its implementation.

**Comment by markheger** [comment]
still a draft since 4 years, https://github.com/IBMStreams/streamsx.documentation/blob/gh-pages/docs/_drafts/java-function-dev-guide.markdown
Testing as described in an SPL environment is ok since having Junit tests for Java native functions might be a over the top.
