### ISSUE TITLE
Feedback for /docs/4.1/messaging/kafka-operators-getting-started/ - consistent region

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#63]
Re:  Consistent region.  Why do the user need to do this?  What do these parameters give the user?

To start a consistent region with a KafkaConsumer, you must:

Place an @consistent annotation above the operator

Specify the partition parameter - This example is for a single-partition topic, but for a three-partition topic you can simple specify: partition: 0,1,2;
Specify triggerCount parameter for operatorDriven trigger - The trigger count gives the approximate number of messages between checkpointing. If you are using a periodic trigger for your consistent region, you do not need to specify this. Here is the KafkaConsumer from the KafkaConsistentRegionConsumerSimple sample:

**Comment by Alex-Cook4** [comment]
Made some changes, but I'm not sure I know exactly what you mean, so am not sure if I agree or not. I'm closing as solved, but feel free to reopen and make specific recommendations that I can review.
