### ISSUE TITLE
Feedback for /docs/4.1/messaging/kafka-operators-getting-started/ - feel disjoint

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#64]
As I read through this quickly, I find the document really disjoint, and still have a hard time following.

I cannot quite pinpoint exactly why.  Perhaps it's the formatting, perhaps it's how the information is presented.  For example, we seem to just jump for one topic to another, without really explaining the background.

For example:
Configure the Kafka Producer to produce messages.

For someone who is new:
* What is a Kafka Producer?  Is it producing messages to the kafka server?  or producing messages to a Streams application
* Why do I care?

The alignment in the document is not consistent, making it hard to scan through and process the information.

**Comment by Alex-Cook4** [comment]
Made some changes to formatting to improve flow and clarify Kafka Producer vs. Consumer (since it's easy to get confused that the Producer is a Sink, while the Source is a Consumer). Closing for now, let me know if there are more comments.
