### ISSUE TITLE
Feedback for /docs/drafts/java-op-dev-guide-outline-sam/ - simplify sample

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.documentation#7]
`client may optionally extend from AbstractOperator`

I would strongly encourage use of the provided patterns in the samples jar as simplify operator development and allow focus on the actual functionality of the operator.

which then conflicts somewhat with `steps to create this operator in Studio` as Studio creates its own simpler patterns.

Also on the use of annotations, I would show the simple cases, using the provided defaults so, for example

```
@PrimitiveOperator
public class MyOp ...
```

not

```
@PrimitiveOperator(name="MyOp")
public class MyOp ...
```

Especially for the port annotations, the current page has a hugely complex set of annotations, where in reality it's probably something like:

```
@InputPortSet(cardinality=1)
@OutputPortSet(cardinality=1)
```

**Comment by chanskw** [comment]
I agree with Dan... we should show the minimum.

**Comment by Alex-Cook4** [comment]
This feedback has been incorporated. Thanks @ddebrunner.
