### ISSUE TITLE
Feedback for /docs/latest/python/python-appapi-devguide/ - missing image

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.documentation#73]
Missing image in Splitting Stream section.
Please fix @juliabamford.

Thanks!

**Comment by juliabamford** [comment]
@chanskw I checked in a fix, but not sure I have authorization to close this issue.

**Comment by chanskw** [comment]
image still seems broken.. giving it a few mins to see if it refreshes

**Comment by juliabamford** [comment]
It showed up in the preview. Not sure if that means anything...

**Comment by chanskw** [comment]
fixed... need another ../../

**Comment by chanskw** [comment]
if it shows up in the preview, then it means the path is wrong.

The preview uses the path in the dev tree.  The generated code have similar paths, but add an extra layer due to how jekyll generates pretty url.  The only reliable test for this is to use a local server

**Comment by juliabamford** [comment]
Got it. Thanks, Sam.
