### ISSUE TITLE
command line documentation

### ISSUE THREAD

**Issue by Phezzan** [IBMStreams/streamsx.documentation#81]
I would like to understand how I may automate builds / automated testing.  

I need to understand how to 
- build standalone applications
- provide them with data
- collect the output 

All without a GUI.  

Thanks for any suggestions!

**Comment by chanskw** [comment]
Thanks for the suggestions!

Here's some resources that may help you while we work on this:

This is a general hub for anyone trying to get started:
https://developer.ibm.com/streamsdev/new-to-streams/

Here's the Streams Quick Start Guide that shows you how to build and run application at the command line.
https://developer.ibm.com/streamsdev/docs/streams-quick-start-guide/

We have a Java Mock Framework, which can enable you to run your automated tests in JUnit.

@ddebrunner - Where should we point users to for getting started information with the Java Mock Framework.  Do you have examples on how you use JUnit for your testing?

Thanks!

**Comment by ddebrunner** [comment]
The Java operator mock framework allows assert based testing (e.g. JUnit) of Java primitive operators. It's documented in the javadoc of the Java operator api, and a couple of samples exist in the sample jar.
In addition some of the toolkits (streamsx.inet at least) use it for testing their Java primitive operators.

Separately you can use the testing mechanism provided in com.ibm.streamsx.topology for Java application api to write assert based testing of Streams applications. While the api is aimed at Java developers, you can build an application using Java that includes SPL operators and then run and test it in standalone or distributed. In this case you may want to write a single SPL composite that contains any SPL code to be tested and then invoke that from the Java Application API and run tests against the composite's output stream. This framework allows you to submit data into the sub-graph under test and verify that the correct output was received.
