### ISSUE TITLE
Feedback for /docs/4.1/java/java-appapi-devguide/

### ISSUE THREAD

**Issue by debmalya** [IBMStreams/streamsx.documentation#85]
Caused by: java.lang.ClassNotFoundException: com.ibm.json.java.JSONObject

Not able to compile  StreamsContextFactory.getEmbedded().submit(topology)

I have  com.ibm.streamsx.topology.jar and com.ibm.streams.operator.jar . Do not have JSON4j.jar 

Could you advise ?

**Comment by chanskw** [comment]
@wmarshall484 @ddebrunner Can you please take a look?

**Comment by wmarshall484** [comment]
JSON4j.jar is one of the jar files looked for in the host's Streams install.

@debmalya, are you running on a host with a Streams install, and has the environment been configured with streamsprofile.sh?

**Comment by debmalya** [comment]
Thanks that problem got solved. It was my mistake.
